### ISSUE TITLE
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (72)

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/socius#1]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
$ npm list @stencil/core
folia-ui@0.0.3 /Users/tim/repos/socius
└── @stencil/core@0.15.2 
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
```
$ npm start/npm build
[Error] Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
```

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by timofeysie** [comment]
Using node version 8.16.1.
```
$ npm start

> folia-ui@0.0.3 start /Users/tim/repos/socius
> stencil build --dev --watch --serve


[ ERROR ]  Missing binding /Users/tim/repos/socius/node_modules/node-sass/vendor/darwin-x64-57/binding.node Node Sass
           could not find a binding for your current environment: OS X 64-bit with Node.js 8.x Found bindings for the
           following environments: - OS X 64-bit with Node.js 10.x This usually happens because your environment has
           changed since running `npm install`. Run `npm rebuild node-sass` to download the binding for your current
           environment. Error: Missing binding
           /Users/tim/repos/socius/node_modules/node-sass/vendor/darwin-x64-57/binding.node Node Sass could not find a
           binding for your current environment: OS X 64-bit with Node.js 8.x Found bindings for the following
           environments: - OS X 64-bit with Node.js 10.x This usually happens because your environment has changed
           since running `npm install`. Run `npm rebuild node-sass` to download the binding for your current
           environment. at module.exports (/Users/tim/repos/socius/node_modules/node-sass/lib/binding.js:15:13) at
           Object.<anonymous> (/Users/tim/repos/socius/node_modules/node-sass/lib/index.js:14:35) at Module._compile
           (module.js:653:30) at Module._extensions..js (module.js:664:10) at Object.require.extensions..js
           (/Users/tim/repos/socius/node_modules/@stencil/core/dist/sys/node/index.js:1:50607) at Module.load
           (module.js:566:32) at tryModuleLoad (module.js:506:12) at Function.Module._load (module.js:498:3) at
           Module.require (module.js:597:17) at require (internal/module.js:11:18)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! folia-ui@0.0.3 start: `stencil build --dev --watch --serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the folia-ui@0.0.3 start script.
```

**Comment by timofeysie** [comment]
Solution: 
```
$npm rebuild node-sass
```

**Comment by timofeysie** [comment]
Not related but there is still a runtime error:
```
[ ERROR ]  sass: src/components/button/button.scss, line: 193: src/components/button/button.scss
           Undefined variable: "$check-thickness".
    L193:    } 
```

**Comment by timofeysie** [comment]
Tried:
```
$ nvm use 12
$ npm rebuild node-sass
/Users/tim/.node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
11 warnings and 3 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tim/repos/socius/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/tim/.nvm/versions/node/v12.9.1/bin/node" "/Users/tim/repos/socius/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/tim/repos/socius/node_modules/node-sass
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
```

**Comment by timofeysie** [comment]
It seems like using node version 8.16.1 fixes this issue.
It's been a good six months since I've looked at this code.  There was a lot of work on the development branch, but when merging it into master, the micro-interactions are broken, or so it seems.  This issue however is fixed.
